### ISSUE TITLE
Implement release and deploy actions

### ISSUE THREAD

**Issue by arufanov** [a5lab/tabr#160]
Implement release and deploy actions
* [ ] pass database password instead of ... 
* [ ] pass google analytics id

userful links:
* https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
* https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

@yurichervoniy 
* FYI

**Comment by arufanov** [comment]
@yurichervoniy 
* https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow  "To run a workflow manually, the workflow must be configured to run on the workflow_dispatch event. To trigger the workflow_dispatch event, your workflow must be in the default branch. For more information about configuring the workflow_dispatch event, see "[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch)"." to test this issue I will push to main directly.

**Comment by arufanov** [comment]
Summary:
* deploy will be not implemented due to env variables and network connectivity. 
* release implemented and discarded due to a) github actions is archived: https://github.com/actions/create-release https://github.com/actions/upload-release-asset b) a new actions doesn't have ability to setup different assets name and filename c)  mvn-release require right to push to git. Summary: unable to find good flow.

P.S. code

```
#
# Build and release application
#
name: Release application

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: maven
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm packages
        shell: bash
        run: npm install uglifycss uglify-js -g
      - name: Verify package
        shell: bash
        run: mvn verify
      - name: Create archive
        shell: bash
        run: cd ./target && tar -zcvf tabr.tar.gz tabr*.jar
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          files: ./target/tabr.tar.gz
          draft: true
          prerelease: false


```
