### ISSUE TITLE
Think about how to organize message.properties

### ISSUE THREAD

**Issue by arufanov** [a5lab/tabr#62]
Think about how to organize message.properties

**Comment by arufanov** [comment]
@yurichervoniy 
lets;
* create message for resource and single common (messages or tabr)
* like this

```
  labels:
    read: "Read"
    readmore: "Read more"
    posted: "Posted at"
    actions: "Actions"
    filter_name: "Filter"
  buttons:
    new: "New"
    add: "Add"
    edit: "Edit"
    close: "Close"
  footer:
    company: "Company"
  navigation:
    breadcrumbs:
      home: "Home"
      scm_analytics: "SCM analytics"
    metamenu:
      account: "Account"
      signup: "Sign up"
      signin: "Sign in"
      signout: "Sign out"

    mainmenu:
      company: "Company"
      contact_us: "Contact us"
    listmenu:
       title:
        tags: "Tags"
        categories: "Categories"
        new_authors: "New authors"
        recent_articles: "Recent articles"
        relevant_articles: "Relevant articles"

```
